version: '3'

services:
  redis:
    image: redis:8-alpine@sha256:becdda6c7f4b3fb42e42fd7f120bbf5c54c4caaaf16f26da24e4563d2c1f0576
    restart: unless-stopped
    command: '--io-threads 2'
    ports:
      - 6379:6379

