version: '3'

services:
  redis:
    image: redis:8-alpine@sha256:0804c395e634e624243387d3c3a9c45fcaca876d313c2c8b52c3fdf9a912dded
    restart: unless-stopped
    command: '--io-threads 2'
    ports:
      - 6379:6379

